### ISSUE TITLE
uta_20180821.pgd.gz dump seems to be incomplete

### ISSUE THREAD

**Issue by AleksandrSl** [biocommons/uta#218]
At the end of `uta_20171026` dump three `REFRESH MATERIALIZED VIEW` statements are executed for views `exon_set_exons_fp_mv`, `tx_exon_set_summary_mv`, `tx_def_summary_mv`.  

However restoration of uta_20180821 ends with `GRANT` statements without any `REFRESH MATERIALIZED VIEW`, and requests to database from hgvs are failed with 
```
RuntimeError: generator didn't stop after throw()
self = <contextlib._GeneratorContextManager object at 0x7f68ff390ed0>
type = <class 'psycopg2.errors.ObjectNotInPrerequisiteState'>
value = ObjectNotInPrerequisiteState('materialized view "tx_def_summary_mv" has not been populated\nHINT:  Use the REFRESH MATERIALIZED VIEW command.\n')
```

Refresh of these three views in database solves problem.

**Comment by reece** [comment]
Hi @AleksandrSl-

I'm sorry about this issue. It sounds like you worked around it already.

That db release was updated by a colleague, so I'm a bit fuzzy on details. The loading scripts refresh mat views automatically. However, in this case, he made a minor change that invalidated the mat views, then dumped. I thought the dump had been updated, but your report suggests that this isn't the case.

When did you download this dump?

Sorry about the problems.

**Comment by reece** [comment]
See also https://github.com/biocommons/hgvs/issues/537

**Comment by AleksandrSl** [comment]
Thanks, issue and the solution (https://github.com/biocommons/hgvs/issues/537#issuecomment-450183852) seems to be the same as in biocommons/hgvs#537. **Today** I cloned uta repository, built two images using this [Dockerfile](https://github.com/biocommons/uta/blob/master/misc/docker/uta.dockerfile) and specifying `uta_20180821` and `uta_20171026` as arguments and started containers, then connected to each one using hgvs and run simple variant g to c transformation.
