### ISSUE TITLE
collected notes for next update

### ISSUE THREAD

**Issue by reece** [biocommons/uta#221]
# schema changes
* drop sqlalchemy
* protein assoc in tx record
* overhaul genes: use tax_id as primary id
* exon set fingerprint table w/enum
* schema migration (yoyo, likely)
* separate alignment regions from features (i.e., CDS, exons)
* 1° class alignment objects w/ids
* store full tx-level cigar, including introns
* consider using fully-justified alignments w/cigars
* features and feature projections

# data changes
* support refseq, lrg, ensembl
* gene
* enable custom transcripts

# processing
* load from gff3
* automated loading process → much faster updates

# architecture changes
* backends: RDS + sqlite backends
* REST interface
* continue docker deployment
* UTA Python client (rather than direct sql)

**Comment by akeeeshi** [comment]
Hi @reece 

Is there an expected release date for this upcoming update?

**Comment by smrgit** [comment]
Hi @reece -- any news on a possible UTA data update?

**Comment by reece** [comment]
This issue was closed by stalebot. It has been reopened to give more time for community review.  See [biocommons coding guidelines](https://biocommons.org/contributing/coding-guidelines/) for stale issue and pull request policies.  This resurrection is expected to be a one-time event.
