### ISSUE TITLE
ncbi-parse-gbff error

### ISSUE THREAD

**Issue by ypchan** [biocommons/uta#224]
![image](https://user-images.githubusercontent.com/33273919/79436306-49d25600-8003-11ea-9ad2-72db2b08b56d.png)

![image](https://user-images.githubusercontent.com/33273919/79436385-5fe01680-8003-11ea-91d3-0468c3b237d9.png)

Dear sir, 
Your python script **ncbi-parse-gbff** doesn't work. I have checked the source code, and discovered a bug at **line 140 and 144**.  The function **Bio.SeqIO.parse()** requires a file rather than a file handler.
thanke you for your great work.
by cyp

**Comment by reece** [comment]
@ypchan Confirmed. This is now fixed. Thanks for the report.
