### ISSUE TITLE
 is there difference between uta_20150827 and uta_20180821 in above commands?

### ISSUE THREAD

**Issue by nordhuang** [biocommons/uta#226]
$ docker pull biocommons/uta:uta_20150827
$ docker volume create --name=uta_vol 
$ docker run -dit --name uta_20180821 -p 5432:5432 biocommons/uta:uta_20180821
$ docker logs -f uta_20150827

In your example in Installing with Docker (preferred),  is there difference between uta_20150827 and uta_20180821 in above commands? Is it typo?

**Comment by reece** [comment]
Yep, this was a typo. Thanks for the report.
