### ISSUE TITLE
20210129 version not on dockerhub

### ISSUE THREAD

**Issue by korikuzma** [biocommons/uta#232]
20210129 version is seen at http://dl.biocommons.org/uta/ . Is it possible to publish this latest version to dockerhub?

**Comment by sstadick** [comment]
I was also coming here to open a ticket for the same thing.

**Comment by sstadick** [comment]
@reece, is there a schedule for when these updates happen?

**Comment by koopmann** [comment]
in the meantime you can try the image i created: https://hub.docker.com/r/koopmann/uta

**Comment by koopmann** [comment]
Now there is [uta_20210129b](https://hub.docker.com/layers/biocommons/uta/uta_20210129b/images/sha256-eee31414e43d794e88883e0c0c98e01ed525c7cbb98d072baced45f936d33255?context=explore) , so i guess this issue can be closed
