### ISSUE TITLE
Unable to use the uta_20210129 locally or in docker

### ISSUE THREAD

**Issue by LydiePrevost** [biocommons/uta#237]
Hello,
I have been trying to install through docker or locally uta_20210129

1. The latest Docker biocommons/uta does not seem to have any tables 
2. when dumping uta_20210129.pgd.gz I followed the :[installation notes]( https://github.com/biocommons/uta/#installing-from-database-dumps).

- My first run fails :`GRANT

GRANT USAGE ON SCHEMA uta_20210129 TO anonymous;
ERROR:  role "anonymous" does not exist
********* QUERY **********
COMMIT
**************************`
So I created the user.

- My second run does not seem to terminate:
 `REFRESH MATERIALIZED VIEW
REFRESH MATERIALIZED VIEW uta_20210129.tx_def_summary_mv;
REFRESH MATERIALIZED VIEW
REFRESH MATERIALIZED VIEW uta_20210129.tx_similarity_mv;
`
I have been waiting for 3 H, thi sis is the last line of the script, but it seems to hang and I see no tables created.

Could you please help me give the direction the install uta_20210129, my first choice being in Docker.
Thank you

**Comment by korikuzma** [comment]
Hi @LydiePrevost , I used [this](https://github.com/biocommons/uta/issues/228#issuecomment-734134693) solution in order to locally download the 20210129 version.

**Comment by LydiePrevost** [comment]
Hi @korikuzma , Thank you for the help, but the solution you mentioned does not refresh the materialized view and I am getting errors when trying to use the hgvs shell as mentioned  in https://github.com/biocommons/uta/issues/228.

**Comment by korikuzma** [comment]
@LydiePrevost , I know it's been a while, but the `VIEW REFRESH MATERIALIZED VIEW uta_20210129.tx_similarity_mv;` command takes ~5 hours. If you let the process run for this long, does the local installation work for you?

**Comment by koopmann** [comment]
you can also use my docker image i made for latest uta 20210129:
https://hub.docker.com/r/koopmann/uta/tags

**Comment by koopmann** [comment]
This step needs regularily a lot of time, i waited some hours on my local machine.

**Comment by koopmann** [comment]
finally you should see something like: 2023-02-13 09:43:45.379 UTC [1] LOG:  database system is ready to accept connections

**Comment by reece** [comment]
The underlying issue was solved in #228. I'm closing this issue. Please comment in #228 if the issue persists.
