### ISSUE TITLE
sqlite support?

### ISSUE THREAD

**Issue by anderspitman** [biocommons/uta#262]
I see sqlite mentioned in a few places in the biocommons source code, but don't see any documentation for setting it up. Is this still supported?

**Comment by jsstevenson** [comment]
Hi @anderspitman -- to my knowledge, this hasn't been supported for a long time (~a decade?). I think there are some scripts in the repo still that might support exporting the postgres instance to a sqlite DB but they might not be caught up to the current schema.

**Comment by anderspitman** [comment]
Thanks! Any background info on why? Postgres makes sense for the public repo, but for local use sqlite seems like a much better fit.

**Comment by jsstevenson** [comment]
Yeah, totally. Just a matter of available dev resources, I think -- it'd be great to get that built out at some point.
